#datasource specific properties
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jfsseptkart
    username: root
    password: root		

#jpa specific properties
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

message: in development profile  - updated
